Attempt to add postgres metrics via postgres_exporter
spinup-host/spinup pull request #64
Opened 2021-09-28 20:18 UTC by idoqo

The approach I'm currently taking here is to:
- have a generic "DockerService" struct that can be used as a template for docker services we need to run
- Setup a "PostgresExporterService" with all the info needed to run postgres_exporter as a service
- Start the PostgresExporterService on startup*

There are some cleanups needed here e.g
- We should only start the exporter service if there's an existing PostgreSQL cluster. Otherwise, we should start the service when the user creates a new cluster. 
_Alternatively - we can watch for a new cluster and start the exporter service once we detect a PG cluster._

- We need to ensure all services started are in the same network so that they can communicate.
- Maybe we can provide a way for users to disable monitoring?
- The PGExporterService only shows metrics from the PostgreSQL - we will have to provide a Prometheus config where this service (and the API) are [scrape targets](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) so that the user can view all of them in one place

2021-10-05 01:48 UTC, idoqo commented
Hi @viggy28, I did some learning like we discussed and here's some of what I learnt on docker-compose vs docker

### Stopping a running service
I think stopping running services is the same whether we use `docker-compose` or just `docker`. 

**Docker**: `docker stop $container`.
**docker-compose**: `docker-compose stop $service`.

In this case, I feel like they both are equally hard (or easy) I guess :).

Only problem though, is that removing a service from docker-compose.yml and re-running docker-compose up doesn't remove the container (if it's running).

### Starting a new service on startup
With docker-compose, we'd declare all the needed services in the docker-compose file and running `docker-compose up` will start them.

With docker, we'd have to create each container and start them up ourselves (we'd need to keep track of the container name though).

I feel main advantage of docker-compose here is the ease (it automatically knows the services we created).

The disadvantage here is that if one service fails, all other services will be started (but the command returns an error ) so we might not be able to tell. It is also harder to tell which of the services failed (aside logs) and why it failed.

### Starting a new service on demand
With docker-compose, we'd have to update `docker-compose.yml` (or any other docker-compose file) to start a new service.

For docker, we can create the service on the fly and start it.

I think docker-compose has some disadvantage in this case, since we will have to properly update the docker-compose file.

2021-10-05 05:52 UTC, viggy28 commented
Thanks, @idoqo for the detailed explanation.

> Only problem though, is that removing a service from docker-compose.yml and re-running docker-compose up doesn't remove the container (if it's running).

That means, do we need to manually remove the container?

Also, what about connectivity (networking) between containers? IIRC, between all the containers created by a docker-compose service, it works out of the box.

2021-10-05 11:39 UTC, idoqo commented
Yeah, we will have to remove the container manually as in the "stopping a running service" part. 

I think networking isn't a big problem like I initially thought - `docker-compose` automatically creates its network. If we use regular docker, we can also simply create a network on startup, and have all services join that network. Either way, docker will manage the network for us

2021-10-06 06:19 UTC, viggy28 commented
Well, then I am fine with either of the approaches. Go for it whichever you feel confident on :)

2021-10-14 05:43 UTC, viggy28 requested changes

2021-10-15 05:19 UTC, idoqo commented on internal/dockerservice.go
> +					"replaceme",
Yeah, for now the username and passwords are stored in sqlite, so we just pull those and construct the dsn here

2021-10-15 05:43 UTC, viggy28 commented on internal/dockerservice.go
> +		NetworkName:   networkName,
I think so.

2021-10-15 05:45 UTC, viggy28 commented on internal/dockerservice.go
> +		networkExistsError := fmt.Sprintf("network with name %s already exists", ds.NetworkName)
smart.

2021-10-15 05:46 UTC, viggy28 commented on api/create.go
> +			return serviceContainerID, err
makes sense. that's right.

2021-10-15 05:46 UTC, viggy28 commented on README.md
> +#### Data Params
that's fair.

2021-10-16 12:50 UTC, merged